### ISSUE TITLE
Get images for Carousel 

### ISSUE THREAD

**Issue by sameeul** [sameeul/NEXT_SharePoint#1]
Need 3/4 images that goes with NEXT

**Comment by dominiquedifalco** [comment]
I can take this one, but I don't know how to assign it to myself!

**Comment by sameeul** [comment]
NEXT has 4 pillers (Share | Create | Develop | Community). We can have images related to these themes.

**Comment by dominiquedifalco** [comment]
@sameeul  for the pillars, do you have a description of each or a reason they are the pillars? I haven't seen anything on the website
